version: '3'

vars:
    REGISTRY: v2.registry.fohet.cz
    REGISTRY_NAMESPACE: robin_ilyk
    IMAGE_NAME_NTB: os-ntb
    IMAGE_NAME_WORKSTATION: os-workstation
    TAG_DATEPART:
        sh: date +%Y.%m.%d
    TAG_SUMPART:
        sh: sha256sum build.sh | awk '{print substr($0, 1, 6)}'
    TAG: "{{.TAG_DATEPART}}-{{.TAG_SUMPART}}"
    IMG_NTB: "{{.REGISTRY}}/{{.REGISTRY_NAMESPACE}}/{{.IMAGE_NAME_NTB}}:{{.TAG}}"
    IMG_WORKSTATION: "{{.REGISTRY}}/{{.REGISTRY_NAMESPACE}}/{{.IMAGE_NAME_WORKSTATION}}:{{.TAG}}"

tasks:
    default:
        deps:
            - task: ntb
            - task: workstation

    getver-*:
        vars:
            REPO: "{{index .MATCH 0}}"
        cmds:
            - |
                curl -L \
                  -H "Accept: application/vnd.github+json" \
                  -H "X-GitHub-Api-Version: 2022-11-28" \
                  https://api.github.com/repos/{{.REPO}}/releases | jq -r 'map(select (.prerelease == false)) | .[0].tag_name'

    ntb:
        cmds:
            - task: build-ntb
            - task: push-ntb
            -   task: rebase
                vars:
                    IMAGE: "{{.IMG_NTB}}:{{.TAG}}"

    workstation:
        cmds:
            -   task: build-workstation
            -   task: push-workstation
            -   task: rebase
                vars:
                    IMAGE: "{{.IMG_WORKSTATION}}:{{.TAG}}"

    build-workstation:
        vars:
          SOURCE_SUFFIX: "-nvidia"
        requires:
            vars:
                - IMG_WORKSTATION
        cmds:
            - task: build
              vars:
                  TAG: "{{.IMG_WORKSTATION}}"
                  SOURCE_SUFFIX: "{{.SOURCE_SUFFIX}}"

    build-ntb:
        vars:
          SOURCE_SUFFIX: "-main"
        requires:
            vars:
                - IMG_NTB
        cmds:
            - task: build
              vars:
                  TAG: "{{.IMG_NTB}}"
                  SOURCE_SUFFIX: "{{.SOURCE_SUFFIX}}"

    build:
        internal: true
        requires:
            vars:
                - TAG
                - SOURCE_SUFFIX
        cmds:
            - docker buildx build 
                -f Containerfile 
                --build-arg SOURCE_SUFFIX={{.SOURCE_SUFFIX}}
                --tag {{.TAG}}
                --load .

    push-ntb:
        cmds:
            - docker push {{.IMG_NTB}}

    push-workstation:
        cmds:
            - docker push {{.IMG_WORKSTATION}}

    rebase:
        requires:
            - IMAGE
        cmds:
            - "sudo rpm-ostree rebase ostree-unverified-registry:{{.IMAGE}}"
